# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  
  commands:
    - pip install xgi[docs]
    - docs/source/conf.py --output $READTHEDOCS_OUTPUT/html/ docs/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

formats:
  - pdf
  - epub