coverage:
  precision: 2
  round: down
  range: 60..85
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.1
        removed_code_behavior: removals_only # off, removals_only, adjust_base
    patch: off