coverage:
  precision: 2
  round: down
  range: 60..85
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.5
    patch:
      default:
        # basic
        target: 0